Sprint 1
VicDoom/praktikum.messenger pull request #1
Opened 2023-12-17 15:25 UTC by VicDoom

2023-12-26 10:52 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу, есть пара замечаний, без которых не могу принять работу:
1. Нет сервера на express
2. Нет ссылки на макеты

2023-12-26 10:52 UTC, podlovchenko commented on src/components/button-back/button-back.hbs
> +</div>
В проекте некоторые файлы с кодом не заканчиваются переводом строки. Однако, перевод строки в конце файла (EOF) очень важен: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-12-26 10:52 UTC, podlovchenko commented on src/components/button-back/button-back.css
> +    & > div {
Лучше никогда не использовать теги в селекторах, всегда предпочитая классы. Вот хорошая заметка на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-12-26 19:44 UTC, VicDoom commented on src/components/button-back/button-back.hbs
> +</div>
- добавил сервер express
- добавил ссылку на макет в README.md
- исправил eof в hbs файлах

2023-12-26 19:44 UTC, VicDoom commented on src/components/button-back/button-back.css
> +    & > div {
изменил селекторы по тегам на селекторы по вложенным классам

2023-12-26 19:45 UTC, VicDoom commented on src/components/button-back/button-back.css
> +    & > div {
@podlovchenko спасибо!

2023-12-27 07:14 UTC, podlovchenko requested changes

2023-12-27 07:14 UTC, podlovchenko commented on server.cjs
> +const port = 3001;
Сервер по заданию должен запускаться на 3000 порту

2023-12-27 07:14 UTC, podlovchenko commented on server.cjs
> +const port = 3001;
Лучше дать возможность поменять порт через конфигурацию переменных окружения: const PORT = process.env.PORT || 3000; Если не задан порт, тогда будет 3000 по умолчанию.

2023-12-27 07:14 UTC, podlovchenko commented on package.json
> +    "start": "vite",
По заданию
11. Сборка и запуск проекта должны выполняться по команде npm run start.
12. Для запуска проекта в режиме разработки используйте npm run dev.
Сборка и запуск сервера с раздачей статики

2023-12-27 12:45 UTC, VicDoom commented on server.cjs
> +const port = 3001;
добавил файл .env, в котором содержится переменная окружения PORT

2023-12-27 12:46 UTC, VicDoom commented on package.json
> +    "start": "vite",
- npm run dev: запускает проект в режиме разработки
- npm run start: собирает проект и раздает статику по указанному порту через express

2023-12-27 12:46 UTC, VicDoom commented on package.json
> +    "start": "vite",
@podlovchenko спасибо!

2023-12-27 14:02 UTC, podlovchenko approved these changes
Привет, спасибо за оперативные правки, работу принимаю)

2023-12-31 11:24 UTC, merged